name: CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and push Docker image
      run: |
        docker build -t my_django_app .
        docker tag my_django_app myreg2211.azurecr.io/my_django_app:latest
        az acr login --name myreg2211
        docker push myreg2211.azurecr.io/my_django_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Log in to Azure CLI
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Add SSH key
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Run deployment script on Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ishansVM@$VM_IP << 'EOF'
          az acr login --name myreg2211
          docker pull myreg2211.azurecr.io/my_django_app:latest
          docker run -d -p 8000:8000 myreg2211.azurecr.io/my_django_app:latest
        EOF
      env:
        VM_IP: ${{ secrets.VM_IP }}
