name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Build Docker image
      run: docker build -t my_django_app .

    - name: Log in to Azure Container Registry
      run: az acr login --name myreg2211
      env:
        AZURE_CREDENTIALS: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Tag Docker image
      run: docker tag my_django_app myreg2211.azurecr.io/my_django_app:latest

    - name: Push Docker image to ACR
      run: docker push myreg2211.azurecr.io/my_django_app:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: SSH into Azure VM and deploy
      run: |
        az ssh vm --ip 20.244.45.96
        docker pull myreg2211.azurecr.io/my_django_app:latest
        docker run -d -p 8000:8000 myreg2211.azurecr.io/my_django_app:latest
