name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Build and push Docker image
      run: |
        docker build -t ${{ secrets.ACR_LOGIN_SERVER }}/djangoapp:latest .
        docker push ${{ secrets.ACR_LOGIN_SERVER }}/djangoapp:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Check out the repository
      uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Log in to Azure Container Registry
      run: |
        echo ${{ secrets.ACR_PASSWORD }} | docker login ${{ secrets.ACR_LOGIN_SERVER }} -u ${{ secrets.ACR_USERNAME }} --password-stdin

    - name: Deploy to Azure VM
      run: |
        ssh -o StrictHostKeyChecking=no ishansVM@20.244.45.96 << 'EOF'
          docker pull ${{ secrets.ACR_LOGIN_SERVER }}/djangoapp:latest
          docker stop $(docker ps -a -q) || true
          docker rm $(docker ps -a -q) || true
          docker run -d -p 8000:8000 ${{ secrets.ACR_LOGIN_SERVER }}/djangoapp:latest
        EOF
